name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        (which apt-get && sudo apt-get install perl lcov) || (which brew && brew install lcov) || echo
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
    - name: build
      run: |
        cd build
        cmake --build .
    - name: run tests
      run: |
        cd build
        ctest . -C Debug
    - name: process and upload coverage data
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --remove coverage.info '/Applications/Xcode.app/*' --output-file coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    - uses: actions/upload-artifact@v2
      with:
        name: libDCL ${{matrix.os}}
        path: build/libDCL.*
    - uses: actions/upload-artifact@v2
      with:
        name: NSOFtoXML ${{matrix.os}}
        path: build/Sample_Code/NSOFtoXML/NSOFtoXML
    - uses: actions/upload-artifact@v2
      with:
        name: DumpPkgPart ${{matrix.os}}
        path: build/Sample_Code/PackageUtils/DumpPkgPart
    - uses: actions/upload-artifact@v2
      with:
        name: DumpPkgDir ${{matrix.os}}
        path: build/Sample_Code/PackageUtils/DumpPkgDir
    - uses: actions/upload-artifact@v2
      with:
        name: WatsonEnabler ${{matrix.os}}
        path: build/Sample_Code/PackageUtils/WatsonEnabler
    - uses: actions/upload-artifact@v2
      with:
        name: nespackager ${{matrix.os}}
        path: build/Sample_Code/PackageUtils/nespackager
    - uses: actions/upload-artifact@v2
      with:
        name: pbbookmaker ${{matrix.os}}
        path: build/Sample_Code/PackageUtils/pbbookmaker
    - uses: actions/upload-artifact@v2
      with:
        name: ELFtoNTK ${{matrix.os}}
        path: build/Sample_Code/ToolchainUtils/ELFtoNTK
    - uses: actions/upload-artifact@v2
      with:
        name: ELFtoPKG ${{matrix.os}}
        path: build/Sample_Code/ToolchainUtils/ELFtoPKG
    - uses: actions/upload-artifact@v2
      with:
        name: Rex ${{matrix.os}}
        path: build/Sample_Code/ToolchainUtils/Rex
